### PR TITLE
Log incoming requests to the console.

### PR DESCRIPTION
**Pull request by Natim**
That would ease debugging the client a little. Thanks!

### CODE REVIEW

**Comment by Natim** [comment]
15 pour @tarekziade qui avait prédit que dès qu'on mettrait un middleware ça ferait péter les tests.

**Comment by n1k0** [comment]
Let me apply the patch and tell.

**Comment by n1k0** [comment]
Got `pkg_resources.DistributionNotFound: Paste` on a make serve.

**Comment by Natim** [comment]
J'ai ajouté paste dans les requirements mais ton setup.py à pas dû être redeploy.

    .venv/bin/pip install -e ./

**Comment by leplatrem** [comment]
Even if translogger seems advocated in Pyramid docs http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/logging.html#request-logging-with-paste-s-translogger, I find it quite overkill to introduce Paste just for that :( Moreover, it's not p3.4 compatible!

**Comment by Natim** [comment]
Ok let's find another solution then.

**Comment by leplatrem** [comment]
Appart from nitpicks, LGTM :)

**Comment by Natim** [comment]
Updated with your comments.

**Pull request merged**
