### PR TITLE
Fix comments in the .ini file

### PR DESCRIPTION
**Pull request by ametaireau**

### CODE REVIEW

**Comment by pdehaan** [comment]
Speaking of tests, should Travis run [`make test`](https://github.com/mozilla-services/readinglist/blob/master/loadtests/config/test.ini) or [`make smoke`](https://github.com/mozilla-services/readinglist/blob/master/loadtests/config/smoke.ini)? Or both?

I think @ametaireau made a recent change where `make smoke` runs some oauth tests using a bearer token; see #220 _"Use existing bearer tokens for smoke testing"_.

**Comment by pdehaan** [comment]
I also get an error when trying to run `make smoke`:

```
$ cat config/smoke.ini && make smoke
[loads]
no-dns-resolve = true
include_file = loadtest/*.py, config/*.ini
smoke = True
# This is the bearer token of the readinglist-loadtest@restmail.net user
token = 860c8829667b602914f607354e0992afcd55e6232e15ac0f0b80af8661954b18


% .venv/bin/loads-runner --config=./config/smoke.ini --user-id=pdehaan --server-url=https://readinglist.stage.mozaws.net:443 loadtest.TestBasic.test_all

Duration: 0.46 seconds
Hits: 1
Started: 2015-03-26 21:27:48.731040
Approximate Average RPS: 2
Average request time: 0.44s
Opened web sockets: 0
Bytes received via web sockets : 0

Success: 0
Errors: 1
Failures: 0

1 occurrences of:
    AssertionError: 401 != 201    Traceback:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 322, in run
    self.setUp()
  File "loadtest/__init__.py", line 83, in setUp
    self.create()
  File "loadtest/__init__.py", line 137, in create
    self.assertEqual(resp.status_code, 201)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)


Slowest URL: https://readinglist.stage.mozaws.net:443/v1/articles 	Average Request Time: 0.441443

Stats by URLs:
- https://readinglist.stage.mozaws.net:443/v1/articles	Average request time: 0.441443	Hits success rate: 0.0

Custom metrics:
- 401 : 1
make: *** [smoke] Error 1
```

**Comment by ametaireau** [comment]
It actually seems that this make smoke should be more defined, and work across envs. I'm not sure why it fails, will investigate.

Currently, travis is setup to only accept the Basic auth scheme, and I'm not sure it's possible to have it talk to the FxA servers?

**Comment by pdehaan** [comment]
> _"Currently, travis is setup to only accept the Basic auth scheme, and I'm not sure it's possible to have it talk to the FxA servers?"_

Pretty sure it should be possible to talk w/ FxA servers from Travis tests, but cc-ing the experts.
/cc @rfk @ckarlof @vladikoff @jrgm

**Comment by Natim** [comment]
Fixed by https://github.com/mozilla-services/readinglist/commit/c54f9e1bce01954f633d466827f70f14195ab1ba

**Pull request closed without merging**
