### PR TITLE
Service provider with FxA

### PR DESCRIPTION
**Pull request by Natim**
Scope ``readinglist:`` ?

### CODE REVIEW

**Comment by rfk** [comment]
@natim if you need the email address, yes, you'll need at least "profile:email" scope as well as "readinglist".  But consider whether you actually need it, because that one *is* PII that needs careful handling for storage etc.

**Comment by Natim** [comment]
Yes I double checked and we are not asking for the email or the avatar. I think it will be fine with the readinglist only.

@rnewman I plan to change the configuration on the dev server can I ?

**Comment by rnewman** [comment]
Fire away!

**Comment by Natim** [comment]
Ok I am hitting 401 on the readinglist server when using the readinglist bearer token.

**Comment by Natim** [comment]
Ok it works :)

**Pull request merged**
