### PR TITLE
Adding LICENSE file

### LINKED ISSUE #186: Add LICENSE file
I _assume_ we're releasing this under [Mozilla Public License Version 2.0](https://github.com/mozilla-services/loop-server/blob/master/LICENSE), or something, but it may be nice to have an explicit LICENSE file in the root of the project.

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #186

### CODE REVIEW

**Comment by Natim** [comment]
We should also add a classifier here: https://github.com/mozilla-services/readinglist/blob/master/setup.py#L33

I though we decided to go with APL for server side services.

**Comment by ametaireau** [comment]
Yes, you can find exactly what to do in the cliquet repository, see https://github.com/mozilla-services/cliquet/blob/master/setup.py#L36 and https://github.com/mozilla-services/cliquet/blob/master/LICENSE

**Comment by Natim** [comment]
And https://github.com/mozilla-services/cliquet/blob/master/setup.py#L41

**Comment by pdehaan** [comment]
OK, cool. Let's kill this PR and copy the cliquet license.

**Comment by pdehaan** [comment]
Updated (waiting on Travis)

**Pull request merged**
