### PR TITLE
Findout a way to run readinglist loadtest with FxA Bearer tokens.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by ametaireau** [comment]
Please make it enabled / disabled with a flag rather than removing it :)

**Comment by Natim** [comment]
Well if we enabled it we break the FxA login so if you want a flag we should probably fix it with gevent.

**Comment by pdehaan** [comment]
@Natim @leplatrem Will this be fixed in the 1.3.x release when @micheletto shotgun deploys that to stage/prod?

I think we have clients ready to test on Prod w/ oauth.

**Comment by pdehaan** [comment]
Actually, do I need different Bearer tokens for stage vs prod?
I generated a bearer token via https://github.com/mozilla/fxa-oauth-client/blob/master/bin/fxa-oauth.js

### Stage:
```sh
$ http GET https://readinglist.stage.mozaws.net/v1/articles \
  Authorization:"Bearer {{token}}" \
  --verbose

GET /v1/articles HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer {{token}}
Connection: keep-alive
Host: readinglist.stage.mozaws.net
User-Agent: HTTPie/0.9.1



HTTP/1.1 401 Unauthorized
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Next-Page, Total-Records, Last-Modified
Connection: keep-alive
Content-Length: 110
Content-Type: application/json; charset=UTF-8
Date: Thu, 26 Mar 2015 07:06:09 GMT
WWW-Authenticate: Bearer realm="Realm"
WWW-Authenticate: Basic realm="Realm"

{
    "code": 401,
    "errno": 104,
    "error": "Unauthorized",
    "message": "Please authenticate yourself to use this endpoint."
}
```

---

### Prod:
```sh
$ http GET https://readinglist.services.mozilla.com/v1/articles \
  Authorization:"Bearer {{token}}" \
  --verbose

GET /v1/articles HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer {{token}}
Connection: keep-alive
Host: readinglist.services.mozilla.com
User-Agent: HTTPie/0.9.1



HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-Conditions-Accepted
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Next-Page, Total-Records, Last-Modified
Access-Control-Max-Age: 1728000
Backoff: None
Connection: keep-alive
Content-Length: 12
Content-Type: application/json; charset=UTF-8
Date: Thu, 26 Mar 2015 07:13:23 GMT
Last-Modified: 1427354003054
Total-Records: 0

{
    "items": []
}
```

---

Even if I generated the oauth token with `--env stage`

```
$ node bin/fxa-oauth.js \
    token 5882386c6d801776 \
    readinglist \
    -u peter@deseloper.com \
    --url https://oauth.accounts.firefox.com \
    --fxa https://api.accounts.firefox.com/v1 \
    --env stage

fxa info env stage
fxa info user peter@deseloper.com
Password:
fxa http POST https://api-accounts.stage.mozaws.net/v1/account/login
fxa http 200 https://api-accounts.stage.mozaws.net/v1/account/login
fxa http POST https://api-accounts.stage.mozaws.net/v1/certificate/sign
fxa http 200 https://api-accounts.stage.mozaws.net/v1/certificate/sign
fxa http POST https://oauth.stage.mozaws.net/v1/authorization
fxa http 200 https://oauth.stage.mozaws.net/v1/authorization
token: {{token}}
fxa info ok
```

I seem to get a 401; Unauthorized when trying to scrape readinglist.stage:
```
$ http GET https://readinglist.stage.mozaws.net/v1/articles \
    Authorization:"Bearer {{token}}" \
    --verbose

...

HTTP/1.1 401 Unauthorized
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Next-Page, Total-Records, Last-Modified
Connection: keep-alive
Content-Length: 110
Content-Type: application/json; charset=UTF-8
Date: Thu, 26 Mar 2015 07:18:40 GMT
WWW-Authenticate: Bearer realm="Realm"
WWW-Authenticate: Basic realm="Realm"

{
    "code": 401,
    "errno": 104,
    "error": "Unauthorized",
    "message": "Please authenticate yourself to use this endpoint."
}
```

**Comment by rfk** [comment]
> Actually, do I need different Bearer tokens for stage vs prod?

Yes, stage RL config now points to stage FxA servers.

> Even if I generated the oauth token with --env stage

IIRC, the `--fxa` and `--url` arguments will override any value of `--env` specified on the command-line.  So you should use just `--env` without the URLs.  It may be worth filing a bug upstream at fxa-oauth-client to e.g. throw an error if you specify them both.

**Pull request closed without merging**
